export const metadata = {
  title: "Customer Reviews | Flawless DIY – Handyman & Home Improvement in Warwickshire",
  description: "Read customer reviews and testimonials for Flawless DIY's handyman, gardening, and home improvement services in Leamington Spa, Warwick, Kenilworth, Stratford-upon-Avon, and across Warwickshire.",
  keywords: [
    // Gardening priority keywords
    "gardening Warwickshire",
    "gardening Royal Leamington Spa",
    "gardening Warwick",
    "gardening Kenilworth",
    "gardening Stratford-upon-Avon",
    "gardening Rugby",
    "gardening Nuneaton",
    "gardening Bedworth",
    "gardening Atherstone",
    "gardening Southam",
    "gardening Alcester",
    "gardening Shipston-on-Stour",
    "gardening Coleshill",
    "gardening Polesworth",
    "gardening Whitnash",
    "gardening Wellesbourne",
    "gardening Studley",
    "gardening Henley-in-Arden",
    "gardening Bulkington",
    "gardening Kineton",
    "gardening Dunchurch",
    "gardening Bishop's Tachbrook",
    // All other locations
    "gardening Newbold Pacey",
    "gardening Bearley",
    "gardening Butlers Marston",
    "gardening Bidford-on-Avon",
    "gardening Baddesley Ensor",
    "gardening Baginton",
    "gardening Broadwell",
    "gardening Brinklow",
    "gardening Barton",
    "gardening Wolston",
    "gardening Barford",
    "gardening Bishop's Itchington",
    "gardening Budbrooke",
    "gardening Beausale",
    "gardening Burton Dassett",
    "gardening Bubbenhall",
    "gardening Long Itchington",
    "gardening Gaydon",
    "gardening Brailes",
    "gardening Baxterley",
    "gardening Barton-on-the-Heath",
    "gardening Burmington",
    "gardening Barcheston",
    "gardening Walcote",
    "gardening Cherington",
    "gardening Birdingbury",
    "gardening Bourton on Dunsmore",
    "gardening Burton Green",
    "gardening Binley Woods",
    "gardening Billesley",
    "gardening Burton Hastings",
    // General and service keywords
    "reviews Flawless DIY",
    "handyman reviews Warwickshire",
    "gardening testimonials Leamington Spa",
    "home improvement reviews Warwick",
    "property maintenance Kenilworth",
    "DIY service reviews Stratford-upon-Avon",
    "Warwickshire handyman testimonials",
    "flawlessdiy reviews",
    "customer feedback handyman Warwickshire",
    "flawlessdiy"
  ],
  openGraph: {
    title: "Customer Reviews | Flawless DIY – Handyman & Home Improvement in Warwickshire",
    description: "Read customer reviews and testimonials for Flawless DIY's handyman, gardening, and home improvement services in Leamington Spa, Warwick, Kenilworth, Stratford-upon-Avon, and across Warwickshire.",
    url: "https://flawlessdiy.co.uk/reviews",
    siteName: "Flawless DIY",
    images: [
      {
        url: "/flawlessdiy_logo.png",
        width: 800,
        height: 600,
        alt: "Flawless DIY Logo",
      },
    ],
    locale: "en_GB",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Customer Reviews | Flawless DIY – Handyman & Home Improvement in Warwickshire",
    description: "Read customer reviews and testimonials for Flawless DIY's handyman, gardening, and home improvement services in Leamington Spa, Warwick, Kenilworth, Stratford-upon-Avon, and across Warwickshire.",
    images: ["/flawlessdiy_logo.png"],
    site: "@flawlessdiy",
  },
};
