import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Flawless DIY | Handyman, Gardening & Home Improvement in Warwickshire",
  description:
    "Flawless DIY offers professional handyman, gardening, and home improvement services in Leamington Spa and across Warwickshire. Local, reliable, and family-run.",
  keywords: [
    // Gardening priority keywords
    "gardening Warwickshire",
    "gardening Royal Leamington Spa",
    "gardening Warwick",
    "gardening Kenilworth",
    "gardening Stratford-upon-Avon",
    "gardening Rugby",
    "gardening Nuneaton",
    "gardening Bedworth",
    "gardening Atherstone",
    "gardening Southam",
    "gardening Alcester",
    "gardening Shipston-on-Stour",
    "gardening Coleshill",
    "gardening Polesworth",
    "gardening Whitnash",
    "gardening Wellesbourne",
    "gardening Studley",
    "gardening Henley-in-Arden",
    "gardening Bulkington",
    "gardening Kineton",
    "gardening Dunchurch",
    "gardening Bishop's Tachbrook",
    // All other locations
    "gardening Newbold Pacey",
    "gardening Bearley",
    "gardening Butlers Marston",
    "gardening Bidford-on-Avon",
    "gardening Baddesley Ensor",
    "gardening Baginton",
    "gardening Broadwell",
    "gardening Brinklow",
    "gardening Barton",
    "gardening Wolston",
    "gardening Barford",
    "gardening Bishop's Itchington",
    "gardening Budbrooke",
    "gardening Beausale",
    "gardening Burton Dassett",
    "gardening Bubbenhall",
    "gardening Long Itchington",
    "gardening Gaydon",
    "gardening Brailes",
    "gardening Baxterley",
    "gardening Barton-on-the-Heath",
    "gardening Burmington",
    "gardening Barcheston",
    "gardening Walcote",
    "gardening Cherington",
    "gardening Birdingbury",
    "gardening Bourton on Dunsmore",
    "gardening Burton Green",
    "gardening Binley Woods",
    "gardening Billesley",
    "gardening Burton Hastings",
    // General and service keywords
    "handyman Warwickshire",
    "gardening Leamington Spa",
    "home improvement Warwick",
    "property maintenance Kenilworth",
    "DIY services Stratford-upon-Avon",
    "local handyman near me",
    "Flawless DIY Warwickshire",
    "affordable handyman Warwickshire",
    "Warwickshire home repairs",
    "kitchen fitting Warwickshire",
    "painting and decorating Leamington Spa",
    "cleaning services Warwickshire",
    "flawlessdiy"
  ],
  openGraph: {
    title: "Flawless DIY | Handyman, Gardening & Home Improvement in Warwickshire",
    description:
      "Flawless DIY offers professional handyman, gardening, and home improvement services in Leamington Spa and across Warwickshire. Local, reliable, and family-run.",
    url: "https://flawlessdiy.co.uk/",
    siteName: "Flawless DIY",
    images: [
      {
        url: "/flawlessdiy_logo.png",
        width: 800,
        height: 600,
        alt: "Flawless DIY Logo",
      },
    ],
    locale: "en_GB",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Flawless DIY | Handyman, Gardening & Home Improvement in Warwickshire",
    description:
      "Flawless DIY offers professional handyman, gardening, and home improvement services in Leamington Spa and across Warwickshire. Local, reliable, and family-run.",
    images: ["/flawlessdiy_logo.png"],
    site: "@flawlessdiy",
  },
}
